name = "Manasvi"

# string slicing
print(name)

print("string slicing without skip value\n")
print(name [0:3])
print(name [-4:-1])
print(name [3:6])
print(name [:4])     #print 0 to 4 number index
print(name [1:])     #print 1 to last index
print(name [:])      #print full string


# string slicing with skip value
print("string slicing with skip value\n")
print(name[0:6:2])   #print 0 to 6 index with skip value 2
print(name[::2])     #print full string with skip value 2       

# string functions
print("string functions\n")
print("length of string is =", len(name))
print("maximum character in string is =", max(name))
print("minimum character in string is =", min(name))
print("count of character 'a' in string is =", name.count('a'))
print("index of character 's' in string is =", name.index('s'))
print("convert string to uppercase =", name.upper())
print("convert string to lowercase =", name.lower())
print("replace character 'M' with 'P' in string =", name.replace('M', 'P'))
print("find character 'v' in string at index =", name.find('v'))
print("check string starts with 'Ma' =", name.startswith('Ma'))
print("check string ends with 'vi' =", name.endswith('vi'))
print("split the string =", name.split('a'))
print("capitalize the string =", name.capitalize())
print("title case the string =", name.title())
print("isalnum check =", name.isalnum())
print("isalpha check =", name.isalpha())
print("isdecimal check =", name.isdecimal())
print("isdigit check =", name.isdigit())
print("islower check =", name.islower())
print("isupper check =", name.isupper())
print("isspace check =", name.isspace())
print("swapcase the string =", name.swapcase())
print("center the string with fill character '*' =", name.center(20, '*'))
print("ljust the string with fill character '#' =", name.ljust(20, '#'))
print("rjust the string with fill character '$' =", name.rjust(20, '$'))
print("zfill the string to make length 20 =", name.zfill(20))
print("strip the string =", name.strip())
print("lstrip the string =", name.lstrip())
print("rstrip the string =", name.rstrip())
print("format the string with age =", "My name is {} and I am {} years old".format(name, 20))
print("f-string format the string with age =", f"My name is {name} and I am {20} years old")
print("join the string with '-' =", '-'.join(name))
print("partition the string with 's' =", name.partition('s'))
print("rpartition the string with 's' =", name.rpartition('s'))
print("encode the string =", name.encode())
print("expandtabs the string with tab size 10 =", "Ma\tna\tsv\ti".expandtabs(10))
print("translate the string =", name.translate(str.maketrans('Mna', 'Pxy')))
print("removeprefix 'Ma' from string =", name.removeprefix('Ma'))
print("removesuffix 'vi' from string =", name.removesuffix('vi'))
print("casefold the string =", name.casefold())
print("foldcase the string =", name.casefold())
print("isprintable check =", name.isprintable())
print("isascii check =", name.isascii())
print("partition the string with 'a' =", name.partition('a'))
print("rpartition the string with 'a' =", name.rpartition('a'))
print("bytes of the string =", bytes(name, 'utf-8'))
print("memory view of the string =", memoryview(bytes(name, 'utf-8')))
print("hash of the string =", hash(name))
print("id of the string =", id(name))
print("ascii of the string =", ascii(name))
print("repr of the string =", repr(name))
print("format map of the string =", "My name is {n}".format_map({'n': name}))
print("casefold the string =", name.casefold())
print("removeprefix 'Ma' from string =", name.removeprefix('Ma'))
print("removesuffix 'vi' from string =", name.removesuffix('vi'))
print("isidentifier check =", name.isidentifier())
print("istitle check =", name.istitle())
print("partition the string with 'a' =", name.partition('a'))
print("rpartition the string with 'a' =", name.rpartition('a'))
print("bytes of the string =", bytes(name, 'utf-8'))
print("memory view of the string =", memoryview(bytes(name, 'utf-8')))
print("hash of the string =", hash(name))
print("id of the string =", id(name))
print("ascii of the string =", ascii(name))
print("repr of the string =", repr(name))
print("format map of the string =", "My name is {n}".format_map({'n': name}))
print("isidentifier check =", name.isidentifier())
print("istitle check =", name.istitle())
print("encode the string =", name.encode())
print("expandtabs the string with tab size 10 =", "Ma\tna\tsv\ti".expandtabs(10))
print("translate the string =", name.translate(str.maketrans('Mna', 'Pxy')))
print("casefold the string =", name.casefold())
print("isprintable check =", name.isprintable())
print("isascii check =", name.isascii())




