d = {}
name = input("enter the name =")
language = input("enter the language =")
d.update({name: language})
name = input("enter the name =")
language = input("enter the language =")
d.update({name: language})
name = input("enter the name =")
language = input("enter the language =")
d.update({name: language})
name = input("enter the name =")
language = input("enter the language =")
d.update({name: language})
name = input("enter the name =")
language = input("enter the language =")
d.update({name: language})
print(d)